

-- Print function for different types


LUA DOSENT HAVE A TRY USE PROGRAMMING BLOCKS MAYBE IDK
    LUA DOSENT HAVE A THROW USE PROGRAMMING BLOCKS MAYBE IDK
end
LUA DOSENT HAVE A CATCH USE PROGRAMMING BLOCKS MAYBE IDK
    print(ee)
end
LUA DOSENT HAVE A FINALLY USE PROGRAMMING BLOCKS MAYBE IDK
    print("finally finally finally finally")
end
